version: 2
updates:
  - package-ecosystem: maven
    directory: "/employee-service"
    schedule:
      interval: daily
      time: '21:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
